insert into diplom_work.dbo.Должность (name) VALUES ('Преподователь')
insert into diplom_work.dbo.Должность (name) VALUES ('Старший преподователь')
insert into diplom_work.dbo.Должность (name) VALUES ('Доцент')
insert into diplom_work.dbo.Должность (name) VALUES ('Профессор')
insert into diplom_work.dbo.Должность (name) VALUES ('Заведующий кафедры')